#!/bin/bash

# ==========================================
# IPsec Fix & Optimization Script
# Generated by Antigravity (Replicating Electron Functionality)
# ==========================================

LOG_FILE="/var/log/ipsec-fix.log"
exec > >(tee -a ${LOG_FILE}) 2>&1

echo "--- Starting IPsec Reset & Fix [$(date)] ---"

# 1. Hard Cleanup
echo "Stopping services..."
systemctl stop strongswan strongswan-starter strongswan-swanctl 2>/dev/null || true
pkill charon || true
pkill starter || true

# 2. Ensure Dependencies
echo "Checking dependencies..."
if ! command -v swanctl >/dev/null 2>&1; then
    echo "Installing StrongSwan..."
    DEBIAN_FRONTEND=noninteractive apt-get update -qq && DEBIAN_FRONTEND=noninteractive apt-get install -y -qq strongswan strongswan-pki libstrongswan-extra-plugins strongswan-swanctl charon-systemd
fi

# 3. Ensure Service Exists (Repair strongswan-swanctl.service)
echo "Ensuring service exists..."
CHARON_PATH=""
# Find charon binary
for p in /usr/lib/ipsec/charon /usr/libexec/ipsec/charon /usr/sbin/charon-systemd /usr/lib/strongswan/charon /usr/libexec/strongswan/charon; do
    if [ -x "$p" ]; then CHARON_PATH="$p"; break; fi
done

if [ -z "$CHARON_PATH" ]; then
    CHARON_PATH=$(which charon-systemd 2>/dev/null)
fi

if [ -n "$CHARON_PATH" ]; then
    echo "Found Charon at: $CHARON_PATH"
    cat <<EOF > /etc/systemd/system/strongswan-swanctl.service
[Unit]
Description=strongSwan IPsec IKEv1/IKEv2 daemon using swanctl
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=$CHARON_PATH
ExecStartPost=/bin/sleep 10
ExecStartPost=-/usr/sbin/swanctl --load-all
ExecReload=/usr/sbin/swanctl --reload
Restart=on-abnormal

[Install]
WantedBy=multi-user.target
EOF
    systemctl daemon-reload
else
    echo "Warning: Could not find charon binary! Skipping service repair."
fi

# 4. Start Service
echo "Starting service..."
systemctl enable strongswan-swanctl 2>/dev/null || true
systemctl restart strongswan-swanctl || true
echo "Waiting 2s for service warmup..."
sleep 2

# Verify Running
if pgrep -x charon >/dev/null; then
    echo "Charon is running."
else
    echo "Charon failed to start! Attempting manual start..."
    nohup $CHARON_PATH >/dev/null 2>&1 &
    sleep 3
fi

# 5. Fix Config Issues
echo "Fixing config issues..."
sed -i '/dpd_delay/d' /etc/swanctl/conf.d/*.conf 2>/dev/null || true
sed -i 's/start_action = trap/start_action = start/g' /etc/swanctl/conf.d/*.conf 2>/dev/null || true

# Ensure unique = replace
grep -q 'unique = replace' /etc/swanctl/conf.d/*.conf || sed -i '/version = 2/a \ \ \ \ \ \ \ \ unique = replace' /etc/swanctl/conf.d/*.conf 2>/dev/null || true

# 6. Reload Configs
echo "Loading configs..."
swanctl --load-all || true

# 7. Upgrade Watchdogs (Smart Mode)
echo "Upgrading Watchdogs..."
for script in /usr/local/bin/ipsec-keepalive-*.sh /usr/local/bin/keepalive-ipsec-*.sh /usr/local/bin/keepalive-gre-*.sh; do
    [ -f "$script" ] || continue
    
    # Extract ID
    ID=$(basename "$script" .sh | grep -oE '[0-9]+$')
    
    # Extract TARGET
    TARGET=$(grep -E '^\s*TARGET=' "$script" 2>/dev/null | head -1 | cut -d= -f2 | tr -d '"; ')
    if [ -z "$TARGET" ]; then
        TARGET=$(grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}' "$script" | head -1)
    fi
    
    # Extract Original Sevice Name
    SVC_NAME=$(basename "$script" .sh)
    
    if [ -z "$ID" ] || [ -z "$TARGET" ]; then
        echo "Skipping $script (No ID/Target)"
        continue
    fi
    
    echo "Upgrading $script (ID=$ID, TARGET=$TARGET)"
    
    cat <<EOF > "$script"
#!/bin/bash
TARGET="$TARGET"
echo "DEBUG: SCRIPT UPDATED BY ANTIGRAVITY"
EOF

    cat <<'EOF' >> "$script"
while true; do
  FAIL=0
  
  # 1. Check Ping
  if ! ping -c 6 -W 2 $TARGET > /dev/null; then
    FAIL=1
  fi
  
  # 2. Check IPsec SA (Prevent Split Brain)
  if [ $FAIL -eq 0 ]; then
      if ! timeout 5 /usr/sbin/swanctl --list-sas --ike tun$ID | grep -E -q "ESTABLISHED|CONNECTING"; then
          echo "Ping OK but NO IPsec SA found for tun$ID! Force Recovery..."
          FAIL=1
      fi
  fi

  if [ $FAIL -eq 1 ]; then
    echo "Connection lost. Initiating recovery..."
    
    # 1. Hard retry (Terminate stale SA)
        echo "Connection lost. Terminating stale connections..."
        timeout 5 swanctl --terminate --ike tun$ID 2>/dev/null
        timeout 5 swanctl --terminate --child tun$ID 2>/dev/null
        sleep 5
        
        # Double tap to be sure
        timeout 5 swanctl --terminate --ike tun$ID 2>/dev/null || true
        
        timeout 5 swanctl --initiate --child tun$ID 2>/dev/null
        
        # Give IKE time to negotiate (Slow network compensation)
        echo "Waiting 50s for IKE negotiation..."
        sleep 50
        # 3. Last resort: Restart service
    sleep 5
  fi
  sleep 10
done
EOF
    chmod +x "$script"
    systemctl enable "$SVC_NAME.service" 2>/dev/null
    systemctl restart "$SVC_NAME.service" 2>/dev/null
done

# 8. Install Global Health Monitor
echo "Installing Health Monitor..."
# Ensure timeout command exists (matched from JS line 571)
command -v timeout >/dev/null 2>&1 || apt-get install -y coreutils
cat <<EOF > /usr/local/bin/ipsec-health-monitor.sh
#!/bin/bash
LOG_FILE="/var/log/ipsec-health.log"
echo "\$(date): Monitor started." >> "\$LOG_FILE"

while true; do
    # Check if swanctl responds within 5 seconds
    if ! timeout 5 swanctl --stats > /dev/null 2>&1; then
        echo "\$(date): VICI Socket Unresponsive! Force Restarting..." >> "\$LOG_FILE"
        
        # Kill logic
        rm -f /var/run/charon.vici /var/run/charon.pid
        pkill -9 charon
        systemctl kill -s SIGKILL strongswan-swanctl 2>/dev/null
        
        sleep 10
        systemctl restart strongswan-swanctl
        sleep 15
    fi
    sleep 30
done
EOF
chmod +x /usr/local/bin/ipsec-health-monitor.sh

cat <<EOF > /etc/systemd/system/ipsec-health-monitor.service
[Unit]
Description=IPSec Health Monitor (VICI Socket Watchdog)
After=strongswan-swanctl.service

[Service]
ExecStart=/usr/local/bin/ipsec-health-monitor.sh
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable --now ipsec-health-monitor
systemctl restart ipsec-health-monitor

echo "--- Fix Complete! ---"
